# S3 -> Snowflake ingestion for daily FX rate files, uploaded manually to
# s3://<bucket>/fx_rates/ for now. Auth uses a Snowflake STORAGE INTEGRATION
# (IAM role trust — Snowflake never holds a long-lived AWS key), not stage
# credentials. This is a real chicken-and-egg setup normally done in two
# passes (the IAM role's trust policy needs values the storage integration
# only generates after it exists, but the integration needs the role's ARN
# as input) — resolved here in one apply by predicting the role ARN from
# account_id + role name (deterministic, doesn't require the role to exist
# yet) rather than waiting on snowflake_storage_integration to be created
# first.

provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}

resource "random_id" "fx_rates_bucket_suffix" {
  byte_length = 4
}

locals {
  fx_rates_bucket_name = "${var.fx_rates_bucket_base_name}-${random_id.fx_rates_bucket_suffix.hex}"
  fx_rates_role_name   = "snowflake-fx-rates-read-role"
  # Deterministic — doesn't depend on aws_iam_role actually existing yet.
  fx_rates_predicted_role_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.fx_rates_role_name}"
}

resource "aws_s3_bucket" "fx_rates" {
  bucket = local.fx_rates_bucket_name
}

resource "aws_s3_bucket_public_access_block" "fx_rates" {
  bucket = aws_s3_bucket.fx_rates.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "fx_rates" {
  bucket = aws_s3_bucket.fx_rates.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Read-only, scoped to just the fx_rates/ prefix in this one bucket.
resource "aws_iam_policy" "fx_rates_read" {
  name        = "snowflake-fx-rates-read-policy"
  description = "Read-only access to the fx_rates/ prefix for Snowflake's storage integration."

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid      = "ListBucketPrefix"
        Effect   = "Allow"
        Action   = ["s3:ListBucket"]
        Resource = [aws_s3_bucket.fx_rates.arn]
        Condition = {
          StringLike = {
            "s3:prefix" = ["fx_rates/*"]
          }
        }
      },
      {
        Sid      = "ReadObjects"
        Effect   = "Allow"
        Action   = ["s3:GetObject"]
        Resource = ["${aws_s3_bucket.fx_rates.arn}/fx_rates/*"]
      },
    ]
  })
}

resource "aws_iam_role" "fx_rates_read" {
  name = local.fx_rates_role_name

  # STORAGE_AWS_IAM_USER_ARN / STORAGE_AWS_EXTERNAL_ID are generated by
  # Snowflake once the storage integration is created — this is the
  # dependency edge that makes Terraform sequence "create the integration"
  # before "finalize the role's trust policy", without the integration
  # itself needing to depend on the role.
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          AWS = snowflake_storage_integration.fx_rates.storage_aws_iam_user_arn
        }
        Action = "sts:AssumeRole"
        Condition = {
          StringEquals = {
            "sts:ExternalId" = snowflake_storage_integration.fx_rates.storage_aws_external_id
          }
        }
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "fx_rates_read" {
  role       = aws_iam_role.fx_rates_read.name
  policy_arn = aws_iam_policy.fx_rates_read.arn
}
